2020-01-05 12:19:10,292 INFO [root] [__init__.py(<module>:10)] - TEST日志器能不能正常工作
2020-01-05 12:19:10,678 INFO [root] [test_login.py(test04_username_have_special_char:66)] - 账号输入特殊字符时输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
