2020-01-05 15:02:00,737 INFO [root] [__init__.py(<module>:10)] - TEST日志器能不能正常工作
2020-01-05 15:02:00,985 INFO [root] [test_login.py(test01_login_success:28)] - 登陆成功接口返回的数据为： {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'c50eaff7-8c34-47c8-8395-693e7264b012'}
2020-01-05 15:02:01,054 INFO [root] [test_login.py(test02_username_is_not_exist:46)] - 账号不存在时输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,107 INFO [root] [test_login.py(test03_password_is_error:56)] - 密码错误时输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,186 INFO [root] [test_login.py(test04_username_have_special_char:66)] - 账号输入特殊字符时输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,255 INFO [root] [test_login.py(test05_username_is_empty:76)] - 账号为空输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,325 INFO [root] [test_login.py(test06_password_is_empty:86)] - 密码为空输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,387 INFO [root] [test_login.py(test07_username_have_chinese:96)] - 账号中有中文输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-01-05 15:02:01,456 INFO [root] [test_login.py(test08_username_middler_have_space:106)] - 账号中有空格输出的数据为： {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
